# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1133, 947)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.centralwidget)
        self.toolBox.setObjectName("toolBox")
        self.page_search_DSM = QtWidgets.QWidget()
        self.page_search_DSM.setGeometry(QtCore.QRect(0, 0, 1109, 791))
        self.page_search_DSM.setObjectName("page_search_DSM")
        self.gridLayout = QtWidgets.QGridLayout(self.page_search_DSM)
        self.gridLayout.setContentsMargins(20, 0, 20, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.page_search_DSM)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.cb_dsm_search_kind = QtWidgets.QComboBox(self.page_search_DSM)
        self.cb_dsm_search_kind.setMinimumSize(QtCore.QSize(181, 26))
        self.cb_dsm_search_kind.setMaximumSize(QtCore.QSize(181, 26))
        self.cb_dsm_search_kind.setObjectName("cb_dsm_search_kind")
        self.gridLayout.addWidget(self.cb_dsm_search_kind, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.page_search_DSM)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.edt_dsm_search_keyword = QtWidgets.QLineEdit(self.page_search_DSM)
        self.edt_dsm_search_keyword.setObjectName("edt_dsm_search_keyword")
        self.gridLayout.addWidget(self.edt_dsm_search_keyword, 0, 3, 1, 1)
        self.btn_dsm_search = QtWidgets.QPushButton(self.page_search_DSM)
        self.btn_dsm_search.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/interface/res/interface/btn_search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_dsm_search.setIcon(icon)
        self.btn_dsm_search.setObjectName("btn_dsm_search")
        self.gridLayout.addWidget(self.btn_dsm_search, 0, 4, 1, 1)
        self.gb_dsm_search_result = QtWidgets.QGroupBox(self.page_search_DSM)
        self.gb_dsm_search_result.setObjectName("gb_dsm_search_result")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gb_dsm_search_result)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lst_dsm_search_result = QtWidgets.QListWidget(self.gb_dsm_search_result)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(True)
        self.lst_dsm_search_result.setFont(font)
        self.lst_dsm_search_result.setIconSize(QtCore.QSize(120, 180))
        self.lst_dsm_search_result.setMovement(QtWidgets.QListView.Static)
        self.lst_dsm_search_result.setFlow(QtWidgets.QListView.LeftToRight)
        self.lst_dsm_search_result.setResizeMode(QtWidgets.QListView.Adjust)
        self.lst_dsm_search_result.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.lst_dsm_search_result.setViewMode(QtWidgets.QListView.IconMode)
        self.lst_dsm_search_result.setWordWrap(False)
        self.lst_dsm_search_result.setObjectName("lst_dsm_search_result")
        self.horizontalLayout.addWidget(self.lst_dsm_search_result)
        self.gridLayout.addWidget(self.gb_dsm_search_result, 1, 0, 1, 5)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/interface/res/interface/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_search_DSM, icon1, "")
        self.page_metadata = QtWidgets.QWidget()
        self.page_metadata.setGeometry(QtCore.QRect(0, 0, 1109, 791))
        self.page_metadata.setObjectName("page_metadata")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_metadata)
        self.verticalLayout_2.setContentsMargins(20, 0, 20, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.page_metadata)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.gb_meta_search = QtWidgets.QGroupBox(self.splitter)
        self.gb_meta_search.setObjectName("gb_meta_search")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gb_meta_search)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lst_meta_search_result = QtWidgets.QListWidget(self.gb_meta_search)
        self.lst_meta_search_result.setObjectName("lst_meta_search_result")
        self.gridLayout_4.addWidget(self.lst_meta_search_result, 2, 0, 1, 3)
        self.edt_meta_search_keyword = QtWidgets.QLineEdit(self.gb_meta_search)
        self.edt_meta_search_keyword.setObjectName("edt_meta_search_keyword")
        self.gridLayout_4.addWidget(self.edt_meta_search_keyword, 1, 0, 1, 3)
        self.cb_meta_search_spiders = QtWidgets.QComboBox(self.gb_meta_search)
        self.cb_meta_search_spiders.setObjectName("cb_meta_search_spiders")
        self.gridLayout_4.addWidget(self.cb_meta_search_spiders, 0, 0, 1, 2)
        self.btn_meta_search = QtWidgets.QPushButton(self.gb_meta_search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_meta_search.sizePolicy().hasHeightForWidth())
        self.btn_meta_search.setSizePolicy(sizePolicy)
        self.btn_meta_search.setText("")
        self.btn_meta_search.setIcon(icon)
        self.btn_meta_search.setObjectName("btn_meta_search")
        self.gridLayout_4.addWidget(self.btn_meta_search, 0, 2, 1, 1)
        self.gb_meta_set = QtWidgets.QGroupBox(self.splitter)
        self.gb_meta_set.setObjectName("gb_meta_set")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gb_meta_set)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.gb_meta_set)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.cb_current_video = QtWidgets.QComboBox(self.gb_meta_set)
        self.cb_current_video.setObjectName("cb_current_video")
        self.gridLayout_2.addWidget(self.cb_current_video, 0, 1, 1, 3)
        self.tbl_metadata = QtWidgets.QTableWidget(self.gb_meta_set)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tbl_metadata.setFont(font)
        self.tbl_metadata.setShowGrid(False)
        self.tbl_metadata.setObjectName("tbl_metadata")
        self.tbl_metadata.setColumnCount(0)
        self.tbl_metadata.setRowCount(0)
        self.tbl_metadata.horizontalHeader().setVisible(False)
        self.tbl_metadata.horizontalHeader().setHighlightSections(False)
        self.tbl_metadata.verticalHeader().setVisible(False)
        self.tbl_metadata.verticalHeader().setHighlightSections(False)
        self.gridLayout_2.addWidget(self.tbl_metadata, 1, 0, 1, 4)
        self.btn_clear_tbl_meta = QtWidgets.QPushButton(self.gb_meta_set)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_clear_tbl_meta.sizePolicy().hasHeightForWidth())
        self.btn_clear_tbl_meta.setSizePolicy(sizePolicy)
        self.btn_clear_tbl_meta.setObjectName("btn_clear_tbl_meta")
        self.gridLayout_2.addWidget(self.btn_clear_tbl_meta, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(524, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 2, 1, 1)
        self.btn_write_to_dsm = QtWidgets.QPushButton(self.gb_meta_set)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_write_to_dsm.sizePolicy().hasHeightForWidth())
        self.btn_write_to_dsm.setSizePolicy(sizePolicy)
        self.btn_write_to_dsm.setObjectName("btn_write_to_dsm")
        self.gridLayout_2.addWidget(self.btn_write_to_dsm, 2, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.splitter)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/interface/res/interface/meta.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_metadata, icon2, "")
        self.page_about = QtWidgets.QWidget()
        self.page_about.setGeometry(QtCore.QRect(0, 0, 1109, 791))
        self.page_about.setObjectName("page_about")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/interface/res/interface/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.page_about, icon3, "")
        self.verticalLayout.addWidget(self.toolBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.status_bar = QtWidgets.QStatusBar(MainWindow)
        self.status_bar.setSizeGripEnabled(True)
        self.status_bar.setObjectName("status_bar")
        MainWindow.setStatusBar(self.status_bar)

        self.retranslateUi(MainWindow)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Synology VideoStation Master"))
        self.label_2.setText(_translate("MainWindow", "范围"))
        self.label.setText(_translate("MainWindow", "关键字"))
        self.edt_dsm_search_keyword.setPlaceholderText(_translate("MainWindow", "输入关键字查找(留空表示显示全部视频)"))
        self.gb_dsm_search_result.setTitle(_translate("MainWindow", "找到的VideoStation影片(双击选择)"))
        self.lst_dsm_search_result.setToolTip(_translate("MainWindow", "双击选择影片进行下一步操作"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_search_DSM), _translate("MainWindow", "查找VideoStation视频"))
        self.gb_meta_search.setTitle(_translate("MainWindow", "搜索元数据"))
        self.lst_meta_search_result.setToolTip(_translate("MainWindow", "双击选择元数据自动填充到元数据表格"))
        self.edt_meta_search_keyword.setPlaceholderText(_translate("MainWindow", "输入关键字查找或直接输入url"))
        self.cb_meta_search_spiders.setToolTip(_translate("MainWindow", "选择刮削器"))
        self.gb_meta_set.setTitle(_translate("MainWindow", "元数据"))
        self.label_4.setText(_translate("MainWindow", "当前影片"))
        self.cb_current_video.setToolTip(_translate("MainWindow", "选择要处理的影片"))
        self.btn_clear_tbl_meta.setText(_translate("MainWindow", "清空表格"))
        self.btn_write_to_dsm.setText(_translate("MainWindow", "写入VideoStation"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_metadata), _translate("MainWindow", "刮削元数据与写入VideoStaiton"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_about), _translate("MainWindow", "设置与反馈"))

import ui.res_rc_rc
